// import './01-基础类型';
// import './01-接口';
// import './02-函数类型';
// import './03-类类型';
// import './01-类';
// import './02-继承';
// import './03-多态';
// import './04-修饰符';
// import './05-readonly修饰符';
// import './06-存取器';
// import './07-静态成员';
// import './08-抽象类';
// import './01-函数';
// import './02-可选参数和默认参数';
// import './03-剩余参数';
// import './04-函数重载';
// import './01-泛型';
// import './02-多个泛型参数的函数';
// import './03-泛型接口';
// import './04-泛型类';
// import './05-泛型约束';
// import './01-声明文件';
import './02-内置对象';

document.body.innerHTML = 'test';
